import { legalEntity, paymentCollectionDisclosure, siteConfig } from "@/lib/site";

export type LegalSection = {
  id: string;
  title: string;
  body: string;
};

export type LegalDocument = {
  slug: string;
  breadcrumb: string;
  title: string;
  eyebrow: string;
  metaTitle: string;
  metaDescription: string;
  updated: string;
  intro: string;
  /** Rendered in a callout above the sections. */
  disclosure?: string;
  sections: readonly LegalSection[];
};

const LAST_UPDATED = "February 2026";

export const termsSections: readonly LegalSection[] = [
  {
    id: "electronic-record",
    title: "1. Electronic Record",
    body: "This document is an electronic record under the Information Technology Act, 2000 and the applicable rules thereunder. It is generated by a computer system and does not require any physical or digital signatures.",
  },
  {
    id: "publication",
    title: "2. Publication and Platform",
    body: "These Terms of Use are published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011. They apply to access and use of the domain https://ishswami.in, including the related mobile site and mobile application, together referred to as the Platform.",
  },
  {
    id: "ownership",
    title: "3. Platform Ownership",
    body: "The Platform is owned by IshSwamiTech, a business operated from Pune, Maharashtra, India, providing technology, software, and digital platform services. By using the Platform, you contract with the Platform Owner and agree to these Terms of Use together with any applicable policies incorporated by reference.",
  },
  {
    id: "acceptance",
    title: "4. Acceptance of Terms",
    body: "By accessing, browsing, or otherwise using the Platform, you agree to all terms and conditions stated here. If you do not agree, you should not proceed further. Any additional or conflicting terms proposed by you are expressly rejected unless we agree to them in writing.",
  },
  {
    id: "information",
    title: "5. Accuracy of Information",
    body: "To access and use the Services, you agree to provide true, accurate, and complete information during and after registration. You are responsible for all actions performed through your registered account on the Platform.",
  },
  {
    id: "usage",
    title: "6. Use of Services",
    body: "You agree not to use the Platform or Services for any unlawful, illegal, or forbidden purpose under these Terms or under applicable Indian or local laws. Your use of the Services and Platform is at your own risk and discretion, and you are responsible for independently determining whether the Services meet your requirements.",
  },
  {
    id: "ip",
    title: "7. Intellectual Property",
    body: "The contents of the Platform and the Services are proprietary to us and are licensed to us. This includes, but is not limited to, the design, layout, look, graphics, and presentation of the Platform. You do not acquire any intellectual property rights, title, or interest in those contents by using the Platform.",
  },
  {
    id: "third-party",
    title: "8. Third-Party Links",
    body: "The Platform may contain links to third-party websites. If you access those links, you will be governed by the terms of use, privacy policy, and other policies of those third-party websites. Such links are provided for convenience and additional information only.",
  },
  {
    id: "payment",
    title: "9. Payment Obligations",
    body: "You agree to pay the charges associated with availing the Services. When you initiate a transaction for Services, you enter into a legally binding and enforceable contract with the Platform Owner for those Services. Payment terms may be supplemented by a separate project agreement, invoice, or statement of work.",
  },
  {
    id: "warranty",
    title: "10. No Warranty",
    body: "Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on the website or through the Services for any specific purpose. To the fullest extent permitted by law, we exclude liability for inaccuracies or errors in such materials.",
  },
  {
    id: "liability",
    title: "11. Limitation of Liability",
    body: "To the maximum extent permitted by law, IshSwamiTech shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of profits, data, use, goodwill, or other intangible losses. Nothing in these Terms limits liability where such limitation is not permitted by applicable law.",
  },
  {
    id: "indemnity",
    title: "12. Indemnity",
    body: "You agree to indemnify and hold harmless the Platform Owner, its affiliates, directors, officers, agents, and employees from claims, demands, actions, penalties, or losses arising out of your breach of these Terms, your violation of any law, or your infringement of third-party rights.",
  },
  {
    id: "force-majeure",
    title: "13. Force Majeure",
    body: "Neither party shall be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by events beyond reasonable control, including force majeure events.",
  },
  {
    id: "law",
    title: "14. Governing Law and Jurisdiction",
    body: "These Terms and any dispute or claim relating to them shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Pune, Maharashtra, India.",
  },
  {
    id: "changes",
    title: "15. Changes to These Terms",
    body: "We may modify these Terms at any time without assigning any reason. It is your responsibility to periodically review this page so you remain informed about the current version.",
  },
  {
    id: "contact",
    title: "16. Contact",
    body: "All concerns or communications relating to these Terms must be communicated using the contact information provided on this website.",
  },
];

export const privacySections: readonly LegalSection[] = [
  {
    id: "introduction",
    title: "1. Introduction",
    body: "This Privacy Policy describes how IshSwamiTech and its affiliates collect, use, share, protect, and otherwise process your information and personal data through our website https://ishswami.in and related digital channels. You may browse certain sections without registering, but by using the Platform you agree to this Privacy Policy, the Terms of Use, and applicable service terms under the laws of India.",
  },
  {
    id: "collection",
    title: "2. Collection",
    body: "We collect personal data when you use our Platform, services, or otherwise interact with us. This may include information provided during sign-up or account use such as name, email, phone number, address, login details, project details, and any other information you choose to provide. Where relevant, we may also collect payment, billing, support, booking, and usage data required to operate the service.",
  },
  {
    id: "usage",
    title: "3. Usage",
    body: "We use personal data to provide the services you request, communicate with you about active projects or service requests, maintain security, detect fraud, improve our services, enforce our terms, and comply with legal obligations. Where permitted, we may also use your information for service updates and marketing, subject to your consent and applicable law.",
  },
  {
    id: "sharing",
    title: "4. Sharing",
    body: "We may share personal data with trusted service providers who assist us in operating the Platform, including hosting, analytics, communications, payment processing, and support infrastructure. We may also disclose information when required by law or when necessary to protect the rights, property, or safety of our users, our business, or the public.",
  },
  {
    id: "client-platform-data",
    title: "5. Client Platform, Booking, and Payment Data",
    body: `${paymentCollectionDisclosure} Depending on the platform or service, this may include customer or patient profile details, verification status, bookings, orders, subscriptions, consultation records, invoices, payment transactions, refund records, support requests, and operational records required to provide the booked or purchased service.`,
  },
  {
    id: "cookies",
    title: "6. Cookies and Similar Technologies",
    body: "We use cookies and similar technologies to keep the website functioning, remember your preferences, understand how pages are used, and improve performance. Essential cookies are required for the site to operate and cannot be switched off. You can control or delete non-essential cookies through your browser settings, though some features may not work as expected if you do. Where analytics or third-party services set cookies, those providers process the data under their own policies.",
  },
  {
    id: "security",
    title: "7. Security Precautions",
    body: "We take reasonable security measures to protect your personal data from unauthorized access, loss, misuse, or disclosure. However, no method of transmission or storage is fully secure, and users are responsible for safeguarding login credentials and account access.",
  },
  {
    id: "retention",
    title: "8. Data Retention and Deletion",
    body: "We retain personal data only for as long as necessary to fulfill the purpose for which it was collected or as required by applicable law. You may request account deletion or data assistance through the Platform or by using the contact details below. We may retain certain data where needed for fraud prevention, dispute handling, legal compliance, or legitimate business purposes.",
  },
  {
    id: "rights",
    title: "9. Your Rights",
    body: "You may access, rectify, and update your personal data directly through the Platform where such functionality is available. Depending on your location and applicable law, you may also have additional rights to object to or restrict certain processing.",
  },
  {
    id: "consent",
    title: "10. Consent",
    body: "By visiting our Platform or providing your information, you consent to the collection, use, storage, disclosure, and processing of your information in accordance with this Privacy Policy. Where you provide information about another person, you confirm that you have the authority to do so and that you permit us to use the information under this Policy.",
  },
  {
    id: "changes",
    title: "11. Changes to This Privacy Policy",
    body: "Please review this Privacy Policy periodically for changes. We may update it to reflect changes in our information practices, legal obligations, or service operations.",
  },
  {
    id: "grievance",
    title: "12. Grievance and Contact",
    body: "All concerns or communications relating to this Privacy Policy should be sent using the contact information provided on this website.",
  },
];

export const refundSections: readonly LegalSection[] = [
  {
    id: "services",
    title: "1. Software and Technology Services",
    body: "Refunds for custom software, app development, website development, maintenance, consulting, and other professional services are governed by the signed proposal, statement of work, invoice, or separate written agreement. Work already delivered, approved, or consumed is generally not refundable unless we agree otherwise in writing.",
  },
  {
    id: "client-platform",
    title: "2. Client-Platform Payments",
    body: "For client platforms, IshSwamiTech may collect online payments as the technology and payment collection partner. The actual service, product, booking, subscription, consultation, event, digital content, or deliverable is provided by the respective client or service provider.",
  },
  {
    id: "appointments",
    title: "3. Video and Appointment Services",
    body: "For healthcare and similar time-slot based services, payment is non-refundable once the appointment is confirmed and the reserved slot has been allocated. Missed appointments do not automatically carry forward and any rebooking is subject to live availability unless separately approved in writing.",
  },
  {
    id: "cancellation",
    title: "4. Cancellation Handling",
    body: "Cancellation and refund eligibility depends on the type of service being purchased and the policy shown for that service. If a cancellation or refund is allowed, it will be processed according to the applicable service terms, gateway rules, and the status of work or booking already completed.",
  },
  {
    id: "approved",
    title: "5. Approved Refunds",
    body: "If a refund is approved, it will be initiated to the original payment method where possible. Bank, card, UPI, or payment gateway settlement timelines depend on the payment processor and banking network.",
  },
  {
    id: "requests",
    title: "6. Refund Requests",
    body: "To request a refund review, email us with your project name, invoice number, reason for the request, and any supporting details. We aim to review refund requests within 7 to 10 business days. Once a refund is approved, it will be processed to the original payment source within a further 7 to 10 business days.",
  },
  {
    id: "charges",
    title: "7. Gateway and Processing Charges",
    body: "Payment gateway, bank, or platform charges may be non-refundable where they have already been charged by the payment processor or bank.",
  },
];

export const shippingSections: readonly LegalSection[] = [
  {
    id: "no-physical-shipping",
    title: "1. No Physical Shipping",
    body: "IshSwamiTech primarily provides software, digital products, technology services, client-platform services, and online payment or booking infrastructure. We do not ship physical goods unless a separate written agreement specifically includes physical delivery.",
  },
  {
    id: "digital-delivery",
    title: "2. Digital Service Delivery",
    body: "Software, website, mobile app, cloud, AI, support, consulting, digital product, subscription, booking, event, and platform deliverables are provided electronically through agreed channels such as email, project tools, repositories, cloud environments, production deployments, apps, websites, SMS, WhatsApp, or email.",
  },
  {
    id: "confirmation",
    title: "3. Booking and Service Confirmation",
    body: "For client platforms operated by IshSwamiTech, confirmations and access details may be delivered digitally through the app, website, SMS, WhatsApp, email, or other configured channels. The actual service, consultation, appointment, or deliverable is fulfilled by the listed client or service provider.",
  },
  {
    id: "timelines",
    title: "4. Delivery Timelines",
    body: "Project delivery timelines are defined in the proposal, invoice, or statement of work. Platform confirmations are normally generated after successful booking or order creation and payment confirmation, subject to provider, gateway, and system availability.",
  },
];

export const legalContacts = {
  supportEmail: siteConfig.email,
  supportPhone: siteConfig.phone,
  entityName: legalEntity.displayName,
} as const;

export type LegalSlug =
  | "privacy-policy"
  | "terms-and-conditions"
  | "refund-cancellation"
  | "shipping-delivery";

/**
 * Canonical legal documents. Each maps 1:1 to a route; retired URLs are
 * redirected in next.config.ts rather than duplicated as pages.
 */
export const legalDocuments: Record<LegalSlug, LegalDocument> = {
  "privacy-policy": {
    slug: "privacy-policy",
    breadcrumb: "Privacy Policy",
    title: "Privacy Policy",
    eyebrow: `${legalEntity.displayName} legal`,
    metaTitle: "Privacy Policy",
    metaDescription:
      "How IshSwamiTech collects, uses, shares, and protects personal data across our website, projects, and connected digital services.",
    updated: LAST_UPDATED,
    intro:
      "This policy explains how IshSwamiTech collects and uses information to operate the website, projects, and connected digital services.",
    disclosure: paymentCollectionDisclosure,
    sections: privacySections,
  },
  "terms-and-conditions": {
    slug: "terms-and-conditions",
    breadcrumb: "Terms & Conditions",
    title: "Terms and Conditions",
    eyebrow: `${legalEntity.displayName} legal`,
    metaTitle: "Terms and Conditions",
    metaDescription:
      "The terms governing use of the IshSwamiTech website, services, and connected client platforms.",
    updated: LAST_UPDATED,
    intro:
      "This document is an electronic record and is intended to serve as a formal reference for website, payment gateway, and compliance use.",
    sections: termsSections,
  },
  "refund-cancellation": {
    slug: "refund-cancellation",
    breadcrumb: "Refund & Cancellation",
    title: "Refund & Cancellation Policy",
    eyebrow: `${legalEntity.displayName} legal`,
    metaTitle: "Refund & Cancellation Policy",
    metaDescription:
      "How IshSwamiTech handles refunds and cancellations for service engagements, project invoices, and client-platform payments.",
    updated: LAST_UPDATED,
    intro:
      "This policy applies to service bookings, digital services, and client-platform payments handled through IshSwamiTech.",
    sections: refundSections,
  },
  "shipping-delivery": {
    slug: "shipping-delivery",
    breadcrumb: "Shipping & Delivery",
    title: "Shipping & Delivery Policy",
    eyebrow: `${legalEntity.displayName} legal`,
    metaTitle: "Shipping & Delivery Policy",
    metaDescription:
      "How IshSwamiTech handles digital service delivery and booking confirmations. We do not ship physical goods as part of our standard business model.",
    updated: LAST_UPDATED,
    intro:
      "This policy explains how IshSwamiTech handles digital service delivery and booking confirmations. We do not ship physical goods as part of our standard business model.",
    sections: shippingSections,
  },
};
